# Generated by Django 4.2.7 on 2023-11-29 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['movie__title_sk', 'movie__title_cz', 'movie__title_orig']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title_sk', 'title_cz', 'title_orig']},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
